[package]
name = "videolex-backand-rust"
version = "0.1.0"
edition = "2021"

[dependencies]
lambda_http = "0.17.0"
async-openai = "0.29.0"
axum = "0.8.4"
prost = "0.14.1"
tonic = { version = "0.14.1", features = ["transport"] } # includes server
tonic-prost = "0.14.1"
tokio = "1.47.1"
tonic-reflection = "0.14.1"
serde = "1.0.219"
serde_json = "1.0.143"
map_to_axum_macro = { path = "../map_to_axum_macro" }
tower = "0.5.2"
hyper = { version = "1.7.0", features = ["full"] }
http = "1.2.0"
axum-core = "0.5.2"
futures = "0.3.31"
futures-core = "0.3.31"
http-body = "1.0.1"
bytes = "1.9.0"
futures-util = "0.3.31"
http-body-util = "0.1.2"
hyper-util = "0.1.10"
pin-project = "1.1.8"
tonic-web = "0.14.1"

[build-dependencies]
tonic-prost-build = "0.14.1"
prost-serde = "0.3.0"


tokio = { version = "1", features = ["macros"] }
serde = { version = "1.0.217", features = ["derive"] }

[[bin]]
name = "lambda"
path = "src/lambda.rs"

[[bin]]
name = "axum"
path = "src/axum.rs"

[[bin]]
name = "grpc"
path = "src/grpc.rs"
